{
    "openapi": "3.0.0",
    "info": {
        "title": "Macon-Api-Documentation",
        "description": "This is the endepoint docs from macon-backEnd || api",
        "termsOfService": "",
        "contact": {
            "name": "Interdigitos LDA"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:6800/v1",
            "description": "URL base da API"
        }
    ],
    "paths": {
        "/users/create": {
            "post": {
                "summary": "Cadastro de Administradores",
                "description": "Essa é a rota responsável por cadastrar os administradores do sistema no caso os funionários internos da macon",
                "tags": ["Users"],
                "security": [{"bearerAuth": []}],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/user"
                            },
                            "example": {
                                "user": {
                                    "values": {
                                        "BI": "000814106LA038", 
                                        "password": "testeeeeeeee", 
                                        "email": "testeteste@gmail.com", 
                                        "profileId": "1",
                                        "phoneNumber": "+244 938172286" 
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400": {
                        "description": "Esse Usuário Já Existe na aplicação!"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref":"#/components/schemas/user"
                                }
                            }
                        }
                    } 
                }
            }
        },
        "/login": {
            "post": {
                "summary": "login",
                "description": "Rota para logar na aplicação",
                "tags": ["Users"],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/user"
                            },
                            "example": {
                                "user": {
                                    "values":{
                                        "email": "testeteste@gmail.com",
                                        "password": "testeeeeeeee"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "400": {
                        "description": "Usuário/Password Errada"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "schema": {
                                "type": "object",
                                "$ref":"#/components/schemas/user"
                            }
                        }
                    }
                }
            }
        },
        "/users/edit/alterKey": {
            "post": {
                "summary": "Actualizando Password",
                "description": "Actualizando Password de um usuário admin",
                "tags": ["Users"],
                "security": [{"bearerAuth": []}],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/user"
                            },
                            "example": {
                                "company": {
                                    "values": { 
                                        "id": "8",
                                        "newKey": "123456789",
                                        "confirmNewKey": "123456789"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400": {
                        "description": "Verifique se as senhas coenciden"
                    },
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "items": {
                                        "$ref":"#/components/schemas/user"
                                    }
                                }
                            }
                        }
                    } 
                }
            }
        },
        "/users/all": {
            "get": {
                "summary": "Listagem de os usuários Cadastrados",
                "description": "Listagem de os usuários Cadastrados",
                "tags": ["users"],
                "security": [{"bearerAuth": []}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/user"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/all/{id}": {
            "get": {
                "summary": "Busca Um usuário por ID",
                "description": "Busca Um usuário por ID",
                "tags": ["Users"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "id": "id",
                        "in": "path",
                        "description": "ID da pessoa para busca",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/user"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/update": {
            "put": {
                "summary": "Atualização dos dados de um Usuário",
                "description": "Atualização dos dados de um Usuário",
                "tags": ["Users"],
                "security": [{"bearerAuth": []}],
                "requestBody": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/user"
                        },
                        "example": {
                            "company": {
                                "id": "8",
                                "password": "teste1234",
                                "email": "teste@gmail.com",
                                "phoneNumber": "+244 942693929"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/user"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/delete/{id}": {
            "delete": {
                "summary": "Exclusão de um Usuário",
                "description": "exclusão de um Usuário",
                "tags": ["Users"],
                "security": [{"bearerAuth": []}],
                "parameters": [
                    {
                        "id": "id",
                        "in": "path",
                        "description": "ID do usuário a remover",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "$ref": "#/components/schemas/user"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "user": {
                "type": "object",
                "properties": {
                    "BI": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "profileId": {
                        "type": "number"
                    },
                    "phoneNumber": {
                        "type": "number"
                    }
                }
            },
            "viagem": {
                
            }
        }
    },
    "securitySchemes": {
        "bearerAuth": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT"
        }
    }
}